CREATE TABLE USUARIOS (
	USUARIO_NOMBRE varchar(20) NOT NULL,
	USUARIOS_TYPE int,
	USUARIO_KEY int
	PRIMARY KEY (USUARIOS_NOMBRE)
);
INSERT INTO USUARIOS VALUES( 'Adriana','1','315115879');
INSERT INTO USUARIOS VALUES('Mario','1','315115879');
INSERT INTO USUARIOS VALUES('Luis Enrique','2','201');
INSERT INTO USUARIOS VALUES('El coordi','3','301');
INSERT INTO USUARIOS VALUES('Dios','4','401');
/* -- */

CREATE TABLE ALUMNOS (
	USUARIO_KEY int NOT NULL,
	ALUMNO_CONTRASEÑA varchar(15),
	USUARIO_NOMBRE varchar(20),
	ALUMNO_PREPA int,
	ALUMNO_GRUPO int,
	ALUMNO_PUNTAJE int,
	ALUMNO_PARTIDAS int,
	PRIMARY KEY (USUARIOS_KEY)
);
INSERT INTO INVOICE VALUES('315115879','fierro','Adriana','6','501','3','5');
INSERT INTO INVOICE VALUES('315115879','arre','Mario','6','516','2','3');
/* -- */

CREATE TABLE PROFESORES (
	USUARIO_KEY int NOT NULL,
	USUARIO_NOMBRE varchar(20),
	PROFESOR_CONTRASEÑA varchar(15),
	PROFESOR_ASIGNATURA varchar(15),
	PROFESOR_PREPA int,
	PRIMARY KEY (USUARIOS_KEY)
);
INSERT INTO PROFESORES VALUES('201','Luis Enrique','historia');
/* -- */

CREATE TABLE COORDINADORES (
	USUARIO_KEY int NOT NULL,
	USUARIO_NOMBRE varchar(20),
	CORDI_CONTRASEÑA varchar(15),
	PRIMARY KEY (USUARIOS_KEY)
);
INSERT INTO USUARIOS VALUES('301','El coordi','1234',);
/* -- */

CREATE TABLE ADMINS (
	USUARIO_KEY int NOT NULL,
	USUARIO_NOMBRE varchar(20),
	ADMI_CONTRASEÑA varchar(15),
	PRIMARY KEY (USUARIOS_KEY)
);
INSERT INTO USUARIOS VALUES('401','Dios','hola');


