<?php
	$asignaturas=array ("MATEMATICASIV","FISICAIII","LENGUAESPA","HISTORIAUNIVIII","LOGICA","GEOGRAFIA","DIBUJOII","LENGEXTRINGLESIV","EDUCESARTISTIV","EDFISICAIV","ORIENTACIONEDUIV","INFORMATICA",
	"MATEMATICASV","QUIMICAIII","BIOLOGIAIV","SALUD","HISTORIAMEXII","ETIGRECOLATI","LENGEXTRINGLESV","ETICA","EDFISICAV","EDUCESARTV","ORIENTAEDUV","LITERATURAUNI",
	"DERECHO","LITEMXIBERO","INGLESVI","PSICOLOGIA","MATEMATICASVI","DIBUJOCONSTII","FISICAIV","QUIMICAIV","BIOLOGIAV","GEOGRAFIAECO","INTROCIENSOCIALES","PROBLEMASOCPOLITMX",
	"MODELADOII","HISTORIACULTURA");

	$conexion = mysqli_connect("localhost","root","","prueba2");
	foreach ($asignaturas as $arre)
	{
		$consulta = 'DROP TABLE IF EXISTS '.$arre.';
						CREATE TABLE '.$arre.' (
						UNIDAD char(1) DEFAULT NULL,
						INDICADOR int(11) NOT NULL AUTO_INCREMENT,
						PREGUNTA varchar(100) DEFAULT NULL,
						RESPUESTA_correcta varchar(40) DEFAULT NULL,
						RESPUESTA_uno varchar(40) DEFAULT NULL,
						RESPUESTA_dos varchar(40) DEFAULT NULL,
						RESPUESTA_tres varchar(40) DEFAULT NULL,
						PRIMARY KEY ("INDICADOR")
					) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;
	
					LOCK TABLES '.$arre.' WRITE;
					UNLOCK TABLES;';
		$query = mysqli_query($conexion,$consulta);		
	}
?>