<?php
	$con=$_GET['contra'];
	$ch=str_split($con);
	$cade="";
	for($x=0;$x<5;$x++)
	{
		$wi=rand(0,9);
		$cade=$cade.$wi;
	}
	$carac=0;
	foreach($ch as $p)
	{
		$nu=ord($p);
		$carac+=$nu;
	}
	$cade=$cade.$carac;
	for($x=0;$x<strlen($con);$x++)
	{
		$wi=(ord($ch[$x])>>1)-4;
		$cade=$cade.chr($wi);
	}
	
	$cad=array();
	$arreglo=array();
	$cont=strlen($con);
	for($i=0;$i<$cont;$i++)
	{
		$car=substr($con,$i,1);
		array_push($cad,$car);
	}
	$mul=ceil($cont/5);
	$contadorpal=0;
	for($x=0;$x<$mul;$x++)
	{
		$eje=array();
		for($y=0;$y<5;$y++)
		{
			if($contadorpal<$cont)
				array_push($eje,$cad[$y]);
			else
				array_push($eje,'');
			$contadorpal++;
		}
		array_push($arreglo,$eje);
		for($g=0;$g<5;$g++)
			if($cad!='\0')
				array_shift($cad);
	}
	$grr=array();
	for($y=0;$y<5;$y++)
		for($x=0;$x<$mul;$x++)
			array_push($grr,$arreglo[$x][$y]);
	$grr=implode("",$grr);

	$h='Texto: '.$con.'<br/>playfair("'.$grr.'",5)';
	$cant=ceil(strlen($grr)/2);
	$cade=$cade.substr($grr,0,$cant);
	echo $cade;
?>